name: Build and Test

on:
  push:
    branches:
    - main

jobs:
  build_and_test:
    name: Build and test
    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Azure Functions Core Tools
      shell: pwsh
      run: |
        npm install -g azure-functions-core-tools@3 --unsafe-perm true

    - name: Setup .NET SDK 3.1 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Clear NuGet local cache
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        dotnet nuget locals all --clear

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dir
        dotnet restore .

    - name: Build solution
      shell: pwsh
      run: |
        dir
        dotnet build . -c Debug -v minimal

    - name: Run function app background
      shell: pwsh
      run: |
        dir
        # ./run-functionapp.ps1
        $rootDir = $pwd.Path
        cd ./src/FunctionApp
        Start-Process -NoNewWindow func start
        Start-Sleep -s 60
        cd $rootDir

    - name: Test solution
      shell: pwsh
      run: |
        dir
        # ./run-tests.ps1
        $rootDir = $pwd.Path
        cd ./test/FunctionApp.Tests
        dotnet test . -c Debug
        cd $rootDir
